# Generated by Django 3.2 on 2021-12-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidate_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.CheckConstraint(check=models.Q(age__gte=18), name='age_gte_18'),
        ),
    ]
