# Generated by Django 3.2 on 2021-12-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidate_age_gte_18'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidate',
            name='age_gte_18',
        ),
    ]
